stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - docker build -t yd_assistant .

test-job:
  stage: test
  script:
    - docker run --rm yd_assistant pytest -s -v

deploy-job:
  stage: deploy
  script:
    - docker-compose up -d
