services:
  bot:
    container_name: 'direct_assistant'
    build:
      dockerfile: docker/bot/Dockerfile
      context: .
    image: direct_assistant
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_ID: ${BOT_ID}
      BOT_URI: ${BOT_URI}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      TOKEN_URL: ${TOKEN_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8081:8000"
    command: [ "python", "/app/bot/main.py" ]
    networks:
      - bot_network
    restart: always

  auth:
    image: direct_assistant
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_ID: ${BOT_ID}
      BOT_URI: ${BOT_URI}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      TOKEN_URL: ${TOKEN_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8080:8000"
    command: [ "python", "/app/yandex_auth/main.py" ]
    depends_on:
      - bot
    networks:
      - bot_network
    restart: always

  db_redis:
    image: "redis:7.4"
    container_name: db_redis
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_ID: ${BOT_ID}
      BOT_URI: ${BOT_URI}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      TOKEN_URL: ${TOKEN_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - bot_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    networks:
      - bot_network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  redis_data:
  rabbitmq-data:
    driver: local

networks:
  bot_network:
    driver: bridge