services:
  bot:
    container_name: 'direct_assistant'
    build:
      dockerfile: docker/bot/Dockerfile
      context: .
    image: direct_assistant
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_ID: ${BOT_ID}
      BOT_URI: ${BOT_URI}
    ports:
      - "8081:8000"
    command: >
      bash -c "python /app/bot/main.py"
    volumes:
      - .:/app
    networks:
      - bot_network
    restart: always

  auth:
    image: direct_assistant
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      TOKEN_URL: ${TOKEN_URL}
    ports:
      - "8080:8000"
    command: >
      bash -c "python /app/yandex_auth/main.py"
    volumes:
      - .:/app
    depends_on:
      - bot
    networks:
      - bot_network
    restart: always

  db_redis:
    image: "redis:7.4"
    container_name: db_redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - bot_network

volumes:
  redis_data:

networks:
  bot_network:
    driver: bridge